src/__tests__/setup.ts
src/components/Navigation.tsx
tailwind.config.cjs

Created basic theme switcher that adds the `dark` class to the root element depending on the users device system default setting, or upon manual button press where it is then saved to `localStorage`.
Closes #97, #137

Add basic theme switcher

---

.githooks/pre-commit
src/AppWrapper.tsx
src/components/Navigation.tsx
src/components/ShowCard.tsx
src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx
src/helpers/getMovieUtils.ts
src/hooks/context.ts
src/hooks/index.ts
src/screens/AuthScreen.tsx
src/screens/DashboardScreen.tsx
src/types/index.ts

Creating this PR (as a draft rn) to get some more eyes on the authentication process. Instead of splitting the user out of the session, we now just have the session. You can still access the user via `session.user`. Then a profile context was added as well to show the data in the public DB.
A few specifics to check:
- Login
- Signup
- Browser close and refresh
- Account delete and rename
- Add to watch queue
- Logout
I also updated the pre-commit hook as it was not blocking the commit.
Let me know what you think here or on discord!

Profile Context

---

src/screens/ShowDetailsScreen.tsx

Searching a movie without any US streaming providers displays an element 'Sorry, no information for this movie.' 
Semantically, we can easily change this if needed.
Closes #177

177 bug US

---

src/components/SearchInput.tsx
src/screens/SearchResultsScreen.tsx

Use vanilla HTML form validation to require the search input. Since this can be overridden client side, we also check for the input in the loader and throw an error if it does not exist. This causes the PageNotFound screen to be rendered. 
fixes #203

203 bug empty search

---

src/components/Providers.tsx
src/types/tmdb.ts

Added loading state so nothing is returned until we have to correct provider data. Also made the type declarations all optional as this was causing errors if `US` existed, but `flatrate` did not.
fixes #195

Fix bug where 'No providers' message flashes briefly on all screens

---

src/__tests__/screens/movieScreen.test.tsx
src/components/ShowCard.tsx

Conditionally render add/remove queue buttons on show card based on profile state and data.
- If user is not logged in, no buttons are shown
- If user is logged in
- & show is not in queue, "Add" button is shown
- & show is in queue, "Remove" button is shown
- Removed check for buttons in test. These should be added to a subsequent test where we will log in. 
> NOTE: While the diff looks like there were big changes, this is mostly due to the fact I removed the JSX fragment, so everything was shifted over 4 spaces. The real changes start at line 102, plus the useEffect.
Closes #114

114 Feature update queue buttons

---

src/components/Navigation.tsx
src/helpers/getMovieUtils.ts
src/main.tsx
src/screens/DiscoverScreen.tsx
src/screens/index.ts

Created DiscoverScreen component that requests trending movies from MDB. This can be changed to include TV Shows further along as everything rounds out. 
Request looks like: 
```
https://api.themoviedb.org/3/trending/<type>/<time>?api_key=
```
`type` accepts `all`, `movie`, `tv`, or `person`. 
`time` accepts `day`, or `week`.
I envision these parameters will be user controlled with filters.
See #100 for future filters to be added.
Closes #99

99 feat gallery

---

src/__tests__/components/component.test.tsx
src/__tests__/helpers/navigation.ts
src/__tests__/screens/authScreen.test.tsx
src/__tests__/screens/movieScreen.test.tsx
src/__tests__/screens/navigation.test.tsx
src/components/SearchInput.tsx
src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx

Created `__tests__/helpers/navigation.ts` to create abstractions for common navigation options. This will make the tests easier to maintain. If any of these actions change (even just a testid), we now only have to alter a single line of code, rather than all instances of `goHome` or `openMenu`. 
I also made some slight tweaks to the tests. These will continue to get refactored over the coming days as they leave a bit to be desired still.
- #221

Add helper functions to test dir. Refactor tests slightly.

---

src/__tests__/helpers/navigation.ts
src/__tests__/screens/authScreen.test.tsx
src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx

Created tests for almost all cases of invalid login and signup data. This includes:
- Incomplete forms
- Invalid email
- Non-matching passwords
I also implemented the `fakeTimers` method so we do not have to wait 3 seconds for the error message to disappear.
- #199

199 test invalid auth

---

.githooks/pre-commit
docs/contribution-guidelines.md

Made it a bit easier to skip the pre-commit hook. This is especially useful if you are rebasing a number of no-verify commits with a verified commit. 
Run `export NO_VERIFY=1` in your shell to set an env variable. This will be picked up by the pre-commit hook and skip it. 
Run `export NO_VERIFY=` in your shell to clear the env variable.
If you are not already using oh-my-zsh, you can now created your own `gwip` alias. Add the following to your shell rc file:
```
alias gwip="export NO_VERIFY=1 && git add -A && git commit -m \"CI Skipped. --WIP--\" && export NO_VERIFY="
```
Closes #240

Add NO_VERIFY flag check to pre-commit hook. Update docs

---

src/__tests__/routes.tsx
src/__tests__/screens/assets/showData.json
src/__tests__/screens/movieScreen.test.tsx
src/components/Providers.tsx
src/components/ShowCard.tsx
src/helpers/getMovieUtils.ts
src/helpers/getShowUtils.ts
src/screens/DiscoverScreen.tsx
src/screens/SearchResultsScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/types/tmdb.ts

- Created TV Show Request to return TV Shows by a searched query. This data is then passed into a TV Show details request which is identical to how our Movies behave. Closes #227
- Refactored Movie requests to return a custom object with the relevant data we need. This provides a universal object for both Movies and TV Shows, resulting in fewer conditionals across the different types of requests we are using. Closes #234 
- Created TV Show Providers request. Identical to Movies, an ID is passed through to our `Providers` component, invoking the function and returning a list of streaming servcies. Closes #242 
- Misc Type changes. Created interface `ShowData` that operates as our custom return object types. 
This concludes, and Closes #226 
Due to user error, commit history is slightly …

227 feat tv req

---

src/__tests__/routes.tsx
src/__tests__/screens/movieScreen.test.tsx
src/components/ShowCard.tsx
src/main.tsx
src/screens/DiscoverScreen.tsx
src/screens/SearchResultsScreen.tsx
src/screens/ShowDetailsScreen.tsx

Refactor show details screen to allow for movie or tv show. Created a show type prop to be passed to the show card. This then sets the appropriate URL for the details screen. Finally, we can pull the show type out of the URL on the details page to make the appropriate queries.
- #274

Convert show details screen to allow Movie or TV show

---

src/components/Rating.tsx
src/components/ShowCard.tsx
src/components/index.ts
src/screens/ShowDetailsScreen.tsx
src/stories/components/Rating.stories.ts

Using the MUI rating component, created a wrapper class that will display text below the rating and can be further customized in the future if needed. Also added to storybook.
One small change to the logic is that now when there are not ratings, instead of showing "No ratings available" we show a rating with 0 stars and the text "0 ratings".
Closes #443

Rating converted to component

---

.githooks/pre-commit
scripts/lint-staged.sh

There was a bug in my previous pre-commit script where you were unable to leave files in your working directory as they would always get added with `git add -A`. We now get a list of staged files and then only run es-lint on those files. This makes the check slightly faster and allows a dev to leave un-staged files in their working directory while committing others.
Worth noting that the CI still run es-lint on every file. This will ensure the app retains a 100% es-lint pass rate with the changes mentioned above.
Closes #440

Implement lint staged script

---

src/AppWrapper.tsx
src/components/ShowCard.tsx
src/components/ShowCarousel.tsx
src/components/ShowListCard.tsx
src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx
src/components/index.ts
src/screens/SearchResultsScreen.tsx
src/screens/ShowDetailsScreen.tsx
tailwind.config.cjs

The default view on tablet and desktop will now be the list view. On mobile, grid view will be the default. 
The toggle will swap between views. Since the list card does not work on mobile views, the toggle is hidden on those devices. 
Closes #436

Implement list card view on search results

---

src/components/Providers.tsx
src/components/index.ts
src/components/loaders/ProvidersLoader.tsx
src/components/loaders/ShowCardLoader.tsx
src/components/loaders/ShowCarouselLoader.tsx
src/components/loaders/ShowListCardLoader.tsx
src/components/loaders/index.ts
src/screens/DashboardScreen.tsx
src/screens/FeaturedSearchScreen.tsx
src/screens/SearchResultsScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/stories/components/ProvidersLoader.stories.ts
src/stories/components/ShowCardLoader.stories.ts
src/stories/components/ShowCarouselLoader.stories.ts
src/stories/components/ShowListCardLoader.stories.ts

Changed the naming convention from 'Placeholders' to 'Loaders'. The idea here is that placeholders are used when there is no data, loaders are used when awaiting data. If we know there is no data, a loader should not be used as it indicates to the user more content is loading.
Closed #471

Refactor loading components

---

src/components/ShowCarousel.tsx
src/components/loaders/ShowPosterLoader.tsx
src/components/loaders/index.ts
src/hooks/index.ts
src/stories/loaders/ProvidersLoader.stories.ts
src/stories/loaders/ShowCardLoader.stories.ts
src/stories/loaders/ShowCarouselLoader.stories.ts
src/stories/loaders/ShowListCardLoader.stories.ts
src/stories/loaders/ShowPosterLoader.stories.ts

Created show poster loader component and story. Used loader in the carousel component. I also refactored the stories directory to split up loaders as we did in the components dir.
Closes #491

Show poster loader

---

src/components/ShowCarousel.tsx
src/screens/DashboardScreen.tsx
src/screens/ShowDetailsScreen.tsx

Added basic empty state for the carousel. Since the component can accept `null` for data, this is needed. I added an option prop `fallbackText` which will be the text displayed in this empty state. If that prop is not used, default text will be shown. If we do not want to render the carousel when data is null, we should make that conditional in the parent component.
Closes #487

#487 add no data state to carousel

---

src/components/ShowCarousel.tsx
src/components/ShowPoster.tsx
src/index.css
src/screens/DashboardScreen.tsx
src/stories/components/ShowPoster.stories.ts
tailwind.config.cjs

Added a button to remove a single show from the users queue. This will show only on the dashboard queue carousel.
Also created a show poster storybook as that was missed in my initial work.
https://github.com/Thenlie/Streamability/assets/41388783/1a00cb09-3627-4e53-a3a0-28813912f25f
Closes #508

Show poster 'remove from queue' button

---

src/screens/ShowDetailsScreen.tsx

Created a CTA button on the show details screen that is displayed any time you are not logged in. This button will navigate the user to the signup screen.
---
Closes #527

527 Details page sign up CTA

---

src/helpers/getShowUtils.ts
src/screens/SearchResultsScreen.tsx
src/types/tmdb/movie.ts
src/types/tmdb/show.ts
src/types/tmdb/tv.ts

Added alphabetical sorting to the search results screen. This probably won't get used a ton since you will want to see best results first, but the pattern can be used on Discover screen as well. I also added a 'remove sort' button and cache the original results order in local storage.
Additionally I found a bug with my implementation of multi search. It had actually broken TV shows. So I fix that here as well.
Closes #490

Sorting search results

---

src/components/SearchInput.tsx
src/components/TextInput.tsx
src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx
src/components/index.ts
src/components/modals/EditProfileModal.tsx
src/stories/components/TextInput.stories.ts

I've created a custom text component  to replace repetitive input code in the `LoginForm`, `SignupForm`, `EditProfileModal`, and `SearchInput` components.  All props originally passed to the input components can be passed to the new `TextInput` component except for `className` which I noticed was identical across all instances of the inputs and which I've just passed as a prop to the internal components of `TextInput`.
I also noticed that `SearchInput` was originally making use of the `Input` MUI component whereas all the other text inputs were using `FilledInput`.  The `TextInput` manages this by receiving a `variant` prop which can receive either 'filled' or 'outlined'.
There are two instances of inputs on the `SignupForm` and `EditProfileModal` that are making use of the `Select` MUI …

524 refactor text input component

---

src/components/modals/EditProfileModal.tsx
src/helpers/__tests__/validation.test.ts
src/helpers/index.ts
src/helpers/validationUtils.ts
src/screens/auth/SignUpScreen.tsx

Added methods to validate country names and country codes. Implemented these validations on signup and profile edit. These shouldn't ever fail as we are using a drop down, but it is possible if a user edits the client side code.
Closes #587

Country validation

---

src/components/ShowCarousel.tsx
src/components/loaders/ShowCarouselLoader.tsx
src/hooks/__tests__/useGetProfileArray.test.ts
src/hooks/useGetProfileArray.ts
src/screens/FeaturedSearchScreen.tsx
src/screens/dashboard/DashboardGalleryScreen.tsx
src/screens/dashboard/DashboardScreen.tsx
src/screens/search_results/EmptySearchResults.tsx

Now accepts an optional `dataLoading` prop to internally handing rendering loader. Closes #624

Refactor Carousel Loading

---

src/screens/ShowDetailsScreen.tsx

Prevent text overflow in the show details non-logged in button
Closes #635

Show details button fix

---

src/screens/dashboard/DashboardEmptyGallery.tsx
src/screens/dashboard/DashboardGalleryScreen.tsx

Add spacing around empty dashboard gallery header
**Before**
**After**
Closes #657

fix dashboard empty gallery padding

---

TODO.md
src/hooks/useGetProfileArray.ts
src/screens/auth/SignUpScreen.tsx
src/screens/dashboard/DashboardGalleryScreen.tsx
src/screens/dashboard/DashboardScreen.tsx
src/screens/loaders/DashboardGalleryLoader.tsx

This PR resolves the issue we were seeing after signup. Now when you signup, you are properly redirected to the dashboard and no errors are displayed in the console.
This also fixes #607. 
I also found an issue with the dashboard gallery loader. It would flash the empty state and the flex was messed up showing the posters. Both of these issues are fixed.
https://github.com/Thenlie/Streamability/assets/41388783/3e7d2b57-2c08-47c5-9a6d-aefdda68aea4
Closes #644 
Closes #607

fix signup error 😈

---

src/components/OfflineSnackbar.tsx
src/components/index.ts
src/hooks/index.ts
src/hooks/useNetworkStatus.ts
src/hooks/useTrendingShows.ts
src/screens/DiscoverScreen.tsx
src/screens/FeaturedSearchScreen.tsx
src/screens/PageNotFoundScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/screens/auth/AuthLayout.tsx
src/screens/dashboard/DashboardLayout.tsx
src/screens/search_results/SearchResultsScreen.tsx

This snackbar will automatically appear when network connection is lost. When it is regained, it will automatically disappear. The component is set to `isStatic` so it will not disappear after 3 seconds, but the user can still clear the notification.
The custom hook simply return a boolean that is update on network status change. This will likely be used again in #671 and any other offline related tickets.
- Create custom hook to detect network changes
- Create snackbar component to be used to notify users of offline state
- Add snackbar to every screen
- Create #671
If you notice I missed any screen, please let me know. 
Closes #589

Notify users of offline state

---

.gitignore
src/__tests__/screens/assets/showData.ts
src/helpers/getMovieUtils.ts
src/helpers/getShowUtils.ts
src/helpers/getTvUtils.ts
src/helpers/index.ts
src/helpers/showTypeUtils.ts
src/hooks/__tests__/constants.ts
src/hooks/index.ts
src/hooks/usePaginatedData.ts
src/screens/search_results/SearchResultsCards.tsx
src/screens/search_results/SearchResultsHeader.tsx
src/screens/search_results/SearchResultsScreen.tsx
src/stories/constants.ts
src/types/tmdb/movie.ts
src/types/tmdb/show.ts
src/types/tmdb/tv.ts

This PR adds pagination to the search results screen. You can now fetch a new page of search results if it is available. This will be appended to the bottom of the current screen. 
This respects the user sort. If the first page is sorted, it will not be updated on refetch. If the unsort button is clicked, the TMDB sort order is returned.
> NOTE: Had to share a zip since 10 seconds is too long for GitHub 😂 
[Untitled.mov.zip](https://github.com/Thenlie/Streamability/files/13185459/Untitled.mov.zip)
Closes #482

Add pagination to search results screen

---

src/screens/ShowDetailsScreen.tsx

I don't fully understand how this bug was happening, but this fixes it. If we get a runtime of 0, we display "no runtime available" instead.
Closes #659

Fix runtime '0' bug

---

src/components/ShowPoster.tsx
src/screens/ShowDetailsScreen.tsx

Subtle change, but fixed the show poster aspect ratio. This fixes the show poster component as well as the poster on the show details screen.
Closes #662

Fix show poster aspect ration to 2:3

---

src/helpers/getTvUtils.ts
src/helpers/showTypeUtils.ts
src/screens/ShowDetailsScreen.tsx
src/types/tmdb/show.ts
src/types/tmdb/tv.ts

- Render number of seasons for TV Shows.
- Render date range of airtime for TV Shows, `YYYY - YYYY`.
- If TV Show is ongoing, rendering `YYYY - Present`.
- Modified Interfaces and return data.
Closes #653 
Closes #654

TV Detail Enhancements 

---

TODO.md
src/helpers/__tests__/constants.ts
src/helpers/__tests__/dateFormat.test.ts
src/helpers/__tests__/stringFormat.test.ts
src/helpers/dateFormatUtils.ts
src/helpers/stringFormatUtils.ts
src/screens/ShowDetailsScreen.tsx

Created unit tests for `daysAgo` and the show details release date and runtime functions.
I found a small bug in the release date function where if a release_date was present on a tv show but no end_date or next_air_date, it would return null. In this case we should return the release date formatted as a single date, as we do with movies.
Other than the note above, this does not change any functionality or UI.
Created #691

Add unit tests

---

.github/workflows/ci.yml
TODO.md

Added the todo script to the PR automation. This will not run on pre-commit so you can add TODO comments as you work and not need to update the markdown file. Only once the comments are guaranteed to be left in the code will we require them to be added to the document.
The check is done by running a new TODO report. It then compares that file to the existing one. If there is any difference, the CI will fail.
One minor annoyance is that this will fail when todo comments change lines. So when code is added above a TODO comment the markdown file will need to be updated. In my opinion, this is not the end of the world. It ensures the file is always up to date.
Closes #694

Automate TODO script

---

index.html
src/AppWrapper.tsx

By making the body the color of the footer and the app wrapper the background color, we make the scroll overflow color make the footer and nav and keep the app bg the same.
Closes #578

#578 fix scroll overflow color

---

src/__tests__/screens/SearchResultsScreen.test.tsx

#951 was merged without running tests since it came from a fork. As such, there was a small bug in the SearchResultsScreen test. This was fixed by mocking the `IntersectionObserver`.

add mock for intersection observer

---

.babelrc.cjs
.storybook/main.ts
package-lock.json
package.json

Storybook has been broken since updating to v8 a while back. I posted about this in the storybook repo since I could not figure out the issue. https://github.com/storybookjs/storybook/discussions/28350. It turned out to be a small config change that was made required with v8. Adding this in plus a suggested babelrc update. 
This should also unblock all the storybook dependabot PRs.

Fix Storybook

---

src/__tests__/screens/PageNotFoundScreen.test.tsx
src/__tests__/screens/SearchResultsScreen.test.tsx

Mocking console logs in test files where they are expected. This serves two purposes:
1. Removes bloat from the test logs and makes them easier to parse
2. Allows us to `expect` logs to be called with certain messages to ensure our logging works as expected
Closes #937

mock console logs in tests where they are expected

---

.github/dependabot.yml

Group all `@types/` dependencies in dependabot PRs. Should help reduce PR noise and keep types as up-to-date as possible.

add dependabot group for @types dependencies

---

src/screens/ShowDetailsScreen.tsx

This resolves a bug where the title of the cast list was still displayed when no cast members were present in the data.
Working cast
No cast
Closes #1067

Remove cast section when no cast list is provided

---

TODO.md
src/helpers/validationUtils.ts
src/screens/auth/LoginScreen.tsx
src/screens/auth/SignUpScreen.tsx

This PR is aimed at improving the regex for email validation to include emails like city.texas@gmail.com

improve email validation regex in Login and SignUp screens

---

src/__tests__/components/SeasonCard.test.tsx
src/__tests__/constants.ts
src/__tests__/screens/SeasonsScreen.test.tsx
src/__tests__/screens/ShowDetailsScreen.test.tsx
src/components/SeasonCard.tsx
src/helpers/__tests__/constants.ts
src/helpers/__tests__/validation.test.ts
src/helpers/showTypeUtils.ts
src/helpers/stringFormatUtils.ts
src/helpers/validationUtils.ts
src/routes.tsx
src/screens/SeasonsScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/screens/index.ts
src/stories/components/SeasonCard.stories.ts
src/types/tmdb/show.ts

New screen to display Seasons for a TV Show at the route `/details/tv/:id/seasons`. This includes rendering the newly made `SeasonCard` component on `ShowDetailsScreen`. Closes #1134 
Because the displayed data on the `SeasonsScreen` is also provided by the `getTvDetails` request that is made on `ShowDetailsScreen`, data on the `SeasonsScreen` is conditionally requested. If users navigate to the Seasons screen from `ShowDetailsScreen`, data from `ShowDetailsScreen` is passed through the router to prevent unnecessary requests.
On the same note, `SeasonsScreen` is also prepared to operate similarly if the user navigates back to `ShowDetailsScreen`. However, due to `ShowDetailsScreen` making multiple requests beyond show details, it does not make use of it. Created #1164 
This PR includes …

Season Screen & Implementation of SeasonCard

---

.eslintrc.json
src/__tests__/components/ActorCard.test.tsx
src/__tests__/components/EpisodeCard.test.tsx
src/__tests__/components/SeasonCard.test.tsx
src/__tests__/components/ShowCard.test.tsx
src/__tests__/components/ShowListCard.test.tsx
src/__tests__/components/ShowPoster.test.tsx
src/__tests__/constants.ts
src/__tests__/screens/SeasonDetailsScreen.test.tsx
src/__tests__/screens/SeasonsScreen.test.tsx
src/__tests__/screens/ShowDetailsScreen.test.tsx
src/components/EpisodeCard.tsx
src/components/index.ts
src/helpers/getTvUtils.ts
src/routes.tsx
src/screens/SeasonDetailsScreen.tsx
src/screens/SeasonsScreen.tsx
src/screens/index.ts
src/stories/components/EpisodeCard.stories.ts
src/stories/constants.ts
src/types/tmdb/actor.ts
src/types/tmdb/show.ts
src/types/tmdb/tv.ts

This PR is the final merge to complete #673 
- `SeasonDetailsScreen` to render an individual TV Show Season and its episodes. Closes #1136 
- `SeasonDetailsScreen` UI Tests.
- `getTvSeasonDetails` [TMDB Request](https://developer.themoviedb.org/reference/tv-season-details). Closes #1137 
- `SeasonDetails` interface.
- `EpisodeCard` to render individual episods for a given season. Closes #1135 
- `EpisodeCard` UI Tests.
- `EpisodeCard` Storybook.
-  `getTvEpisodeDetails` [TMDB Request](https://developer.themoviedb.org/reference/tv-episode-details). This request provides per episode cast and images not provided by the `getTvSeasonDetails` request. Additionally, the `append_to_response` parameter `videos` is included, enabling future development opportunities to implement trailers, clips, …

SeasonDetailsScreen & EpisodeCard

---

src/components/Navigation.tsx
src/components/SearchInput.tsx
src/components/TextInput.tsx

Focus search input after expanding search on tablet/mobile view. Still does not autofocus in other scenarios. 
Closes #1186

autofocus search input when expanding search on tablet view

---

src/hooks/usePaginatedData.ts

Not sure exactly when this started happening, but actors are now included in our search results data. As far as I remember, this did not used to be the case. For the quick fix here, I have simply removed actors from the search result data.
- #1187 
- #1188 
- #1189
> These tickets will make it so actors can be properly search for, but this will be a larger effort. 
Closes #1234

remove people from show search results

---

src/hooks/useIsInProfileArray.ts

My initial fix is to set the default value to what is currently in the profile array. This seems to work to fix the flicker on the UI. 
> [!NOTE]
>  We might want to spend a bit more time thinking about this, as I still think every card re-renders when one is added to the queue. It feels totally fine to me, but probably a performance issue just waiting to bite us in the 🍑 .
Closes #1233
https://github.com/user-attachments/assets/d3788488-858e-48f8-8753-bb60bf8f1173

Fix queue button flicker
