Thenlie/Streamability

assets/css/style.css

Added transitions to queueboxes

---

assets/css/style.css
assets/js/script.js

Fixed the delete buttons in the watch queue.

Made footer sticky and tweaked mobile responsiveness

---

README.md
src/App.css
src/App.tsx
src/components/SearchInput.tsx
src/main.tsx
src/screens/FeaturedSearch.tsx

Pretty basic additions. Wanted to flesh out an initial directory structure so it is easier for others to build off of. 
I also made some additions to the README that talk about the git strategy. These should probably be moved to a wiki or developer docs of some sort. but the README is the most accessible place right now.
Closes #44

Create basic client directory structure. Update README.md.

---

.gitignore
README.md
package.json
src/components/SearchInput.tsx
src/components/ShowCard.tsx
src/components/ShowCarousel.tsx
src/components/SideNavigator.tsx
src/components/index.ts
src/main.tsx
src/screens/DashboardScreen.tsx
src/screens/LoginScreen.tsx
src/screens/SearchResultsScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/screens/SignupScreen.tsx
src/screens/index.ts

- Create basic search form using react router Form
- Create movie card component. 
- Refine code.

Create initial component structure

---

src/AppWrapper.tsx
src/types/index.ts
src/types/supabase.ts

Create basic types directory to be filled out throughout the project. This stores interfaces and exports them to the rest of the app. 
Closes #73

Create types directory and move User and Session to it

---

src/AppWrapper.tsx
src/components/ErrorMessage.tsx
src/components/SearchInput.tsx
src/components/ShowCard.tsx
src/components/ShowCarousel.tsx
src/components/SideNavigator.tsx
src/hooks/context.ts
src/hooks/index.ts
src/main.tsx
src/screens/DashboardScreen.tsx
src/screens/FeaturedSearchScreen.tsx
src/screens/LoginScreen.tsx
src/screens/PageNotFoundScreen.tsx
src/screens/SearchResultsScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/screens/SignupScreen.tsx
src/screens/index.ts
src/types/supabase.ts

Added some error handling on login and sign up page. This can, and should, be improved. For now, a message is sent to an `ErrorMessage` component which renders on screen. This component could be improve as well as the messages being sent. 
Added explicit return types to functions and updated JSDoc comments accordingly. This is not 100% necessary but it makes the end purpose of the function more clear. 
Closes #68

68 feat auth error handling

---

src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx
src/components/auth/index.ts
src/components/index.ts
src/main.tsx
src/screens/AuthScreen.tsx
src/screens/index.ts

Created auth screen
Moved login and signup to components directory
Updated pathing so login and signup are children of auth
Closes #69

69 refactor authentication

---

.env.template
src/components/ShowCard.tsx
src/helpers/getMovieUtils.ts
src/screens/SearchResultsScreen.tsx
src/types/supabase.ts
src/types/tmdb.ts

Closes #53 
- Setup two utility functions, `getMoviesByName` returns a list of queries movies. `getMoviesDetails` returns details of a given movid id.
- Setup TS Interfaces to each request responses.
- Added MovieDB API key to template .env
Closes #59 
- Created ShowCard component that displays basic movie data per mockup

59-feat-moviecard

---

src/AppWrapper.tsx
src/components/auth/SignupForm.tsx
src/screens/DashboardScreen.tsx
src/screens/SearchResultsScreen.tsx
src/supabase/profiles.ts
src/types/supabase.ts

Create basic user profile methods. These can and will be expanded upon in the future.
Movie info will be added in #80 
Quite a bit of the work was on supabase, there are a few queries saved to make resetting the DB easier. 
Closes #79

79 feat supabase crud

---

README.md
src/screens/PageNotFoundScreen.tsx
src/screens/SearchResultsScreen.tsx

Super small PR just to get documentation on env flags. 
Closes #55

Added env flags to documentation

---

src/components/ShowCard.tsx
src/screens/SearchResultsScreen.tsx

- Refactored SearchResultsScreen to iterate through each movie, requesting movie details
- Iterating through each movie details to render showCard component
- Refactored ratingHandler function

92 feat card layout

---

.githooks/pre-commit
package.json

Created git hook for pre-commit. 
Details on how to use this more in depth will be added to the wiki. Generally, all you should have to do is:
```
npm run setup
```
That should set your .git to look at the folder made in this PR and run those before each commit. You can run git commit with `--no-verify` to skip these hooks.
Closes #67

Create git pre-commit hook

---

src/__tests__/components/component.test.tsx
src/__tests__/routes.tsx
src/components/ShowCard.tsx
src/supabase/profiles.ts

You are now able to add and remove shows from your watch queue. Temporary buttons are added to all show cards to make this possible. Currently buttons are always clickable, this will need to be updated. 
I have created a few other tickets for future work. 
- #112  
- #113
- #114
⚠️ The only big thing that needs changes is the Supabase functions currently return an empty row. I am going to update that to return the new profile but I can not figure out how right now. I have a forum post up on the supabase repo. I am happy to wait until this is done to merge this if that seems better. ⚠️ 
Closes #80

Add watch queue methods to supabase util file

---

.github/workflows/ci.yml

More of a necessary update than a bug
Closes #107

Update node version in github action

---

src/AppWrapper.tsx
src/components/Navigation.tsx

Created basic navigation component that conditionally renders nav links if user is logged in ✔️
Closes #110

110 feat nav

---

package-lock.json
package.json

Installed MUI and MUI Icons
Close #95

Installed MUI and MUI Icons

---

package-lock.json
package.json
postcss.config.cjs
src/index.css
tailwind.config.cjs

Tailwind install and config ✔️
With Reference #119, Close #63 Close #95 
Close #103

103 feat tw

---

docs/contribution-guidelines.md
docs/project-board.md

Added wiki files to repo so they are accessible locally
Closes  #104

Create docs directory and add in files from wiki

---

.githooks/pre-commit
src/components/ShowCard.tsx
src/screens/DashboardScreen.tsx
src/supabase/profiles.ts

- Create GET queue function
- Update add and delete functions to return new profile
- Small change to pre-commit hook as lint-fix changes would not be applied
- Created #141 to address some issues with using the profile data
Closes #124

124 watch queue crud enhancement

---

src/supabase/profiles.ts

This really is an enhancement despite the ticket type.
Closes #86

Update delete profile function to also delete user account

---

.githooks/pre-commit
src/AppWrapper.tsx
src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx
src/screens/DashboardScreen.tsx

70 feat route protection

---

src/AppWrapper.tsx
src/components/Navigation.tsx
src/hooks/context.ts
src/screens/DashboardScreen.tsx
src/supabase/profiles.ts

Redirect on logout.
Clear localstorage
> Something is definitely wonky with my formatting, will get that sorted in #145 
Closes #77

Redirect user on auth changes. Clear data from local storage.

---

index.html
src/index.css
tailwind.config.cjs

Add temporary styling for demo purposes upon theme change.
Closes #140

Update app color on theme change

---

.githooks/pre-commit
src/App.css
src/AppWrapper.tsx
src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx
src/index.css
src/screens/AuthScreen.tsx

Improved login and signup form. All tasks on #149 were done with one exception. That has been turned into another  ticket.
- #156 
Closes #149

149 Enhance Auth Forms

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/test-coverage.md

Create bug, feature, and test issue templates.

Create issue templates

---

src/__tests__/utilities/utilities.test.tsx
src/helpers/dateFormatUtils.ts

This unit test covers the work done in #160 . I have ensured each potential suffix is tested as well as a range of dates with potentially dangerous dates such as the turn of the century. 
I actually found a few bugs in this process, kind of cool!
> NOTE: This function expects the string it receives is formatted correctly. We need to validate this before calling the function. This is being done currently, let's just be sure to not forget it in the future 😅 
Closes #176

Create date util unit tests

---

src/components/ShowCard.tsx

Fixed inability to add/remove movies to watch queue
Closes #175

175 bug queue

---

.eslintrc.json
src/__tests__/screens/assets/movieData.json
src/__tests__/screens/assets/searchData.json
src/__tests__/screens/screen.test.tsx
src/components/ShowCard.tsx
src/screens/SearchResultsScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/types/tmdb.ts

- Prevent duplicate shows being rendered
- Load all results at once, rather than one at a time
- Update test to mock movieDB API calls

Fixed duplication bug

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/test-coverage.md

I would actually love some change suggestions on this PR, happy to update wording, add or remove sections, etc.

Update markdown of issue templates

---

src/__tests__/screens/assets/providerData.json
src/__tests__/screens/authScreen.test.tsx
src/__tests__/screens/movieScreen.test.tsx
src/__tests__/screens/navigation.test.tsx
src/__tests__/screens/screen.test.tsx
src/components/Navigation.tsx
src/components/ShowCard.tsx
src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx
src/screens/ShowDetailsScreen.tsx

Built out a slightly more reasonable directory structure. Will do the same with components soon. As we update the UI, these tests will need to be tweaked. Feel free to ping me if you have questions.
- Enhance site navigation tests
- Add last movieDB request mock
- Add auth screen tests
- Create #199 
- Close #116 
- Close #187

116 screen testing

---

src/screens/ShowDetailsScreen.tsx

If the location data is empty, we now make a new request to movie DB.

Resolve bug by querying new data if none exists

---

src/__tests__/components/component.test.tsx
src/__tests__/screens/movieScreen.test.tsx
src/components/Providers.tsx
src/screens/ShowDetailsScreen.tsx

- Created Providers component that requests streaming services by a given ID, this can also work with TV Show IDs.
- Altered tests to check for rendered image and alt attribute
Closes #161

161 feat logo

---

src/components/ShowCard.tsx
src/screens/SearchResultsScreen.tsx

Updated show card component to use mostly MUI components. 
- #197

Refactor show card component to use MUI components

---

.githooks/pre-commit
src/AppWrapper.tsx
src/components/Navigation.tsx
src/components/SearchInput.tsx
src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx
src/index.css
src/theme.ts

Added MUI theme provider. Moved theme logic to app wrapper.
We will still need to fill out the theme and set all the colors we want. Feel free to do this as you develop.
- #162

162 theme provider

---

src/__tests__/screens/movieScreen.test.tsx
src/components/ShowCard.tsx
src/helpers/getMovieUtils.ts
src/helpers/getTvUtils.ts
src/screens/DiscoverScreen.tsx
src/screens/SearchResultsScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/types/index.ts
src/types/tmdb.ts

Added functions to get movie and tv show recommendations. These pull data from the MovieDB API and convert them to the showData type.
The types have also been updated slightly. We need to keep in mind that almost all fields are optional in the movieDB response as getting back null or undefined results could result in crashes without proper error handling.
- #237

237 feat recommendations

---

package-lock.json
package.json
src/components/ShowCardPlaceholder.tsx
src/components/index.ts
src/screens/SearchResultsScreen.tsx

Create show card skeleton loader. While the package README suggests not creating dedicated components like this, I think it actually makes the most sense for this application. 
- Created #286
- Closes #74

Create showCard skeleton loader

---

.github/CODEOWNERS

288 Create CODEOWNERS

---

src/AppWrapper.tsx
src/theme.ts

Add skeleton loader theme. We will probably want to make a custom MUI palette in the future, but the works for now.
- Closes #286

Add skeleton loader theme

---

src/helpers/getMovieUtils.ts

Loop through array of release dates to find a non-empty rating

---

src/helpers/getTvUtils.ts
src/screens/ShowDetailsScreen.tsx
src/types/tmdb.ts

Conditionally rendering runtime

---

.eslintrc.json
src/AppWrapper.tsx
src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx
src/screens/DashboardScreen.tsx
src/screens/PageNotFoundScreen.tsx
src/supabase/profiles.ts

Added es-lint rule to warn on console logs. Ignored current logs.

---

src/components/ShowCard.tsx
src/screens/ShowDetailsScreen.tsx

ShowCards and DetailsScreen now display star based rating system. Stars are displayed in increments of .5 (this can be changed if needed). 
Closes #166

Added MUI stars for show reviews

---

src/helpers/getMovieUtils.ts
src/helpers/getTvUtils.ts
src/screens/DiscoverScreen.tsx

Created Trending TV request. 
It's worth nothing that the current Trending Movies request has parameters for TV Shows. This can be refactored later if needed. However, on face value I believe two separate requests and states enable more robust filters in the future.
Closes #310

310 feat trending tv

---

src/screens/DashboardScreen.tsx
src/supabase/profiles.ts
src/types/supabase.ts

Add adult flag and country code to supabase profile table. Create setter functions within the app to toggle these values. 
Still need to add validation to the country code logic. The adult toggle may also want a switch or something better for the UI. Let me know if you have any suggestions. 
- Closes #88 
- Closes #209

Add adult flag and country profile setter functions

---

.github/workflows/ci.yml

Explicitly set node version to 16 in the workflow file.

327 Fix CI

---

src/screens/DashboardScreen.tsx

Updated dashboard screen to use MUI components. It will still need some significant improvements, but this is a better foundation to work off of. 
> Note: It might be worth making some global components for things like inputs, buttons, etc. to avoid some of the MUI component clutter.
- Closes #250

Convert dashboard to MUI components

---

src/__tests__/components/component.test.tsx
src/__tests__/screens/authScreen.test.tsx
src/__tests__/screens/movieScreen.test.tsx
src/__tests__/screens/navigation.test.tsx
src/helpers/__tests__/dateFormat.test.tsx

* #426 
I also took this opportunity to restructure the utility tests in a more logical manner.

Disable UI automation tests

---

src/__tests__/routes.tsx
src/components/ShowCard.tsx
src/components/ShowListCard.tsx
src/screens/SearchResultsScreen.tsx
src/stories/components/ShowCard.stories.ts

Initially intended to just clean up the code, but I found a few areas where rendering was basically broken. Fixed those by truncating title text and shrinking button text size.
- #437

Refactor Show Card

---

src/components/Providers.tsx
src/components/ProvidersPlaceholder.tsx
src/components/index.ts
src/stories/components/ProvidersPlaceholder.stories.ts

Created basic providers placeholder component and storybook.
Closes #210

Providers Placeholder

---

src/components/Providers.tsx
src/screens/ShowDetailsScreen.tsx
src/stories/components/Providers.stories.ts

Added the providers component to storybook and made a small refactor on the component. 
Closes #434

Providers storybook

---

src/screens/ShowDetailsScreen.tsx

Mostly a conversion of text to Typography.
Closes #249

Migrate show details screen to MUI

---

src/__tests__/routes.tsx
src/components/ShowCard.tsx
src/components/ShowListCard.tsx
src/hooks/index.ts
src/hooks/useIsInWatchQueue.ts
src/hooks/useIsInWatchQueue.tsx
src/screens/SearchResultsScreen.tsx
src/stories/components/ShowCard.stories.ts
src/stories/components/ShowListCard.stories.ts
src/stories/constants.ts
src/types/supabase.ts

Create a custom hook to check is a show is in the users watch queue. 
> **Note** This does not take in to account the new id format in supabase (showType-showId).

useIsInWatchQueue

---

src/components/Providers.tsx
src/components/ProvidersPlaceholder.tsx
src/stories/components/Providers.stories.ts
src/stories/components/ProvidersPlaceholder.stories.ts

increase height of provider component when empty

---

src/components/Navigation.tsx
src/components/ShowCard.tsx
src/components/ShowListCard.tsx

Remove MUI Box

---

.eslintrc.json
src/AppWrapper.tsx
src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx
src/logger.ts
src/screens/DashboardScreen.tsx
src/screens/PageNotFoundScreen.tsx
src/screens/SearchResultsScreen.tsx
src/supabase/profiles.ts

This is basically just console log wrapper. This makes it so we do not have to check if the environment is dev at each call site, the log will make the check for us. 
Closes #65

Create custom Logger

---

src/AppWrapper.tsx
src/__tests__/screens/assets/movieData.json
src/__tests__/screens/assets/showData.ts
src/components/Navigation.tsx
src/components/Providers.tsx
src/components/Rating.tsx
src/components/ShowCard.tsx
src/components/ShowCarousel.tsx
src/components/ShowListCard.tsx
src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx
src/helpers/__tests__/constants.ts
src/helpers/getMovieUtils.ts
src/helpers/getShowUtils.ts
src/helpers/getTvUtils.ts
src/helpers/index.ts
src/helpers/showFilterUtils.ts
src/screens/DashboardScreen.tsx
src/screens/DiscoverScreen.tsx
src/screens/FeaturedSearchScreen.tsx
src/screens/SearchResultsScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/stories/constants.ts
src/supabase/profiles.ts
src/types/tmdb/show.ts

Updated the search results screen to use a single query to get both movie and tv show results. I also took the opportunity to update the helper export structure by adding an index file.
- Created #482 
Closes #478

Refactor to TMDB multi-search

---

src/AppWrapper.tsx
src/components/ShowCardPlaceholder.tsx
src/components/ShowListCardPlaceholder.tsx
src/screens/SearchResultsScreen.tsx

Refactored the search result screen loading state and the show card placeholder. 
Closes #194

Refactor search results loader

---

src/components/Providers.tsx
src/components/ShowCard.tsx
src/components/ShowCardPlaceholder.tsx
src/components/ShowCarousel.tsx
src/components/ShowCarouselPlaceholder.tsx
src/components/ShowListCard.tsx
src/components/ShowPoster.tsx
src/components/index.ts
src/index.css
src/screens/DashboardScreen.tsx
src/screens/FeaturedSearchScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/stories/components/ShowCarousel.stories.ts

Made a number of styling updates.
- Create Show Poster component
- Refactor Carousel to use Poster
- Switch details to column on mobile
- Add overflow scroll to providers
- Created #487
https://github.com/Thenlie/Streamability/assets/41388783/500c9e88-1274-409f-ae06-bb1b4b8e64d3
Closes #479 
Closes #468 
Closes #486

Details screen mobile refactor

---

src/helpers/__tests__/showSort.test.ts
src/helpers/index.ts
src/helpers/showSortUtils.ts
src/types/tmdb/show.ts
src/types/tmdb/tv.ts

Created a few sort functions for show data and unit tests.
- Rating Count
- Average Rating
- Release Date
- Title (Alphabetically)
- Create #490 
Closes #450

Sort show data functions

---

src/components/Providers.tsx
src/components/ShowCarousel.tsx
src/hooks/useWIndowSize.ts
src/screens/DashboardScreen.tsx
src/screens/FeaturedSearchScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/stories/components/ShowCarousel.stories.ts

Carousel first render bug

---

src/components/ShowCarousel.tsx
src/screens/DashboardScreen.tsx
src/screens/FeaturedSearchScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/screens/loaders/ShowDetailsLoader.tsx
src/screens/loaders/index.ts
src/stories/components/ShowCarousel.stories.ts

Created show details skeleton loader.
Closes #198

Show details loader

---

src/components/ErrorMessage.tsx
src/components/Navigation.tsx
src/components/Providers.tsx
src/components/Rating.tsx
src/components/SearchInput.tsx
src/components/ShowCard.tsx
src/components/ShowCarousel.tsx
src/components/ShowListCard.tsx
src/components/ShowPoster.tsx
src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx
src/components/loaders/ProvidersLoader.tsx
src/components/loaders/ShowCardLoader.tsx
src/components/loaders/ShowCarouselLoader.tsx
src/components/loaders/ShowListCardLoader.tsx
src/components/loaders/ShowPosterLoader.tsx
src/components/modals/ConfirmDeleteModal.tsx
src/components/modals/EditProfileModal.tsx
src/screens/AuthScreen.tsx
src/screens/DashboardScreen.tsx
src/screens/FeaturedSearchScreen.tsx
src/screens/PageNotFoundScreen.tsx
src/screens/SearchResultsScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/screens/loaders/ShowDetailsLoader.tsx

Updated the pattern we are using for creating functional components. This is a more modern way and leverages reacts built in FC type.
Closes #497

Convert components to use React.FC

---

src/screens/SearchResultsScreen.tsx

The view state will now persist through refresh and page close.
Closes #484

View state local storage

---

src/components/EmptySearchResults.tsx
src/hooks/index.ts
src/hooks/useTrendingShows.ts
src/screens/DiscoverScreen.tsx
src/screens/FeaturedSearchScreen.tsx

Created a hook to return a sorted list of trending shows. This merges TV and movies to give a better list. 
Closes #539

539 useTrendingShows hook

---

src/components/EmptySearchResults.tsx
src/components/Navigation.tsx
src/components/Rating.tsx
src/components/ShowCard.tsx
src/components/ShowCarousel.tsx
src/components/ShowListCard.tsx
src/components/auth/LoginForm.tsx
src/components/modals/ConfirmDeleteModal.tsx
src/components/modals/EditProfileModal.tsx
src/helpers/getMovieUtils.ts
src/logger.ts
src/screens/DashboardScreen.tsx
src/screens/PageNotFoundScreen.tsx
src/screens/SearchResultsScreen.tsx
src/screens/ShowDetailsScreen.tsx

Pointing at the feature branch I worked off of, will re-point to develop before merge.
Closes #548

548 Typography update

---

README.md
docs/contribution-guidelines.md
docs/storybook.md
docs/usage.md

Updated README and documentation. Let me know if you have suggestions and be sure to add to it if you notice gaps in the instructions. Trying to make these as comprehensive as possible so others could easily join in the future.
Closes #247

README and Docs update

---

src/components/auth/LoginForm.tsx
src/components/auth/SignupForm.tsx

Added buttons to redirect login to signup and vice versa. Will be blue on hover.
---
Closes #562

Add auth redirect buttons

---

src/components/modals/EditProfileModal.tsx
src/helpers/showSortUtils.ts
src/screens/DashboardScreen.tsx

Added loading states to all the profile edit buttons. Learned about `localeCompare` so I refactored the sort function.
Closes #522

Profile edit loading state

---

TODO.md
package-lock.json
package.json
src/__tests__/components/component.test.tsx
src/__tests__/screens/authScreen.test.tsx
src/__tests__/screens/movieScreen.test.tsx
src/__tests__/screens/navigation.test.tsx
src/index.css
src/supabase/profiles.ts

Create npm script to list todo comments in a file.
Closes #586

List todos

---

src/hooks/index.ts
src/hooks/useGetProfileArray.ts
src/screens/DashboardScreen.tsx
src/supabase/profiles.ts

Added carousels containing the favorites and watched list of a user. You are able to clear each array in total or each show individually per array. Loading animations are shown when this is happening on a poor connection.
I created a custom hook to return each profile array which will automatically update with the profile.

Dashboard carousels

---

src/components/Navigation.tsx
src/main.tsx
src/screens/ShowDetailsScreen.tsx
src/screens/auth/LoginScreen.tsx
src/screens/auth/SignUpScreen.tsx
src/screens/dashboard/DashboardScreen.tsx

Removed `auth` endpoint entirely. `auth/login` -> `login`.
Closes #605

Fix auth endpoint bug

---

.eslintrc.json
src/__tests__/screens/assets/searchData.json
src/__tests__/screens/assets/showData.ts
src/components/Banner.tsx
src/components/index.ts
src/screens/FeaturedSearchScreen.tsx
src/stories/components/Banner.stories.ts

- Component accepts `renderSearchInput` and `renderLogo` props to optionally display them if Banner is needed for multiple contexts.
- Storybook
- Modified data files
**Logo & SearchInput**
**Title Only**

Banner Component

---

.storybook/main.ts
package-lock.json
package.json
src/stories/components/ShowCard.stories.ts
src/stories/components/ShowCarousel.stories.ts
src/stories/components/ShowListCard.stories.ts
src/stories/components/ShowPoster.stories.ts

Update react router config in storybook to fix clicks.
Closes #549

fix storybook clicks

---

src/AppWrapper.tsx
src/components/Navigation.tsx
src/helpers/supabaseClient.ts
src/screens/auth/LoginScreen.tsx
src/screens/auth/SignUpScreen.tsx
src/screens/dashboard/DashboardScreen.tsx
src/supabase/profiles.ts

Only create the Supabase client if the keys exist. This seem to allow UI tests to pass and not impact the app when the keys are present.

Make supabase client conditional

---

src/components/ShowCarousel.tsx
src/components/loaders/ShowCarouselLoader.tsx
src/components/loaders/ShowPosterLoader.tsx
src/hooks/__tests__/useGetProfileArray.test.ts
src/hooks/__tests__/useTrendingShows.test.ts
src/hooks/useGetProfileArray.ts
src/hooks/useTrendingShows.ts
src/screens/loaders/ShowDetailsLoader.tsx
src/stories/loaders/ShowCarouselLoader.stories.ts

- Improve carousel loader and add it to details screen loader.
- Fix loading return in hooks
Closes #636

Refactor carousel loader

---

src/__tests__/routes.tsx
src/components/ShowCard.tsx
src/components/ShowListCard.tsx
src/components/ShowPoster.tsx
src/components/loaders/ShowCardLoader.tsx
src/screens/search_results/SearchResultsCards.tsx
src/stories/components/ShowCard.stories.ts
src/stories/components/ShowListCard.stories.ts

- Update style of show card.
- Update style of show card loader
- Make title clickable on show card and show list card and navigate to details screen
| Before | After |
|--------|--------|
| ![image](https://github.com/Thenlie/Streamability/assets/41388783/a8b5e166-6d55-44b9-afaa-01daa1ba71f5) | ![image](https://github.com/Thenlie/Streamability/assets/41388783/1dbd95aa-e3db-4dc9-b61b-f8205d2a4cbc) |
Closes #667 
Closes #660

Show card refactor

---

src/helpers/__tests__/showFilter.test.ts
src/helpers/getShowUtils.ts
src/helpers/showFilterUtils.ts
src/types/tmdb/show.ts

Remove shows from search results when the `media_type` is person.
Closes #658

fix 'person' media_type bug

---

src/helpers/getMovieUtils.ts
src/helpers/getTvUtils.ts
src/helpers/showTypeUtils.ts

I introduced a bug with #676 as the discover requests were not returning a media type as I thought. This PR adds that media type.

Discover media type

---

src/helpers/dateFormatUtils.ts

Adds a helper function for determining the date some number of days ago.

Add daysAgo helper function

---

src/components/ShowPoster.tsx
src/screens/search_results/SearchResultsScreen.tsx

Fixed when buttons would disappear on refresh and poster profile buttons not working.
Closes #655

fix search results bugs

---

src/components/ShowCarousel.tsx
src/index.css
src/screens/DiscoverScreen.tsx
src/screens/FeaturedSearchScreen.tsx
src/screens/ShowDetailsScreen.tsx
src/screens/dashboard/DashboardScreen.tsx
src/stories/components/ShowCarousel.stories.ts

Added and optional title and button that may be passed to the carousel. 
Closes #498

Add carousel title and button

---

TODO.md
src/screens/dashboard/DashboardScreen.tsx
src/screens/loaders/DashboardLoader.tsx
src/screens/loaders/index.ts
src/stories/loaders/ShowCarouselLoader.stories.ts

Create a skeleton loader on the dashboard screen that is shown while the profile is loading.
Closes #665

Create dashboard skeleton loader

---

src/components/SearchInput.tsx

switch nav input from outlined to filled

switch nav input from outlined to filled

---

src/helpers/showTypeUtils.ts
src/types/tmdb/tv.ts

Fix bug preventing ongoing TV Shows from rendering

Fix TV Show details bug

---

src/__tests__/screens/FeaturedSearchScreen.test.tsx
src/__tests__/screens/LoginScreen.test.tsx
src/__tests__/screens/PageNotFoundScreen.test.tsx
src/__tests__/screens/SearchResultsScreen.test.tsx
src/__tests__/screens/ShowDetailsScreen.test.tsx
src/__tests__/screens/SignUpScreen.test.tsx
src/screens/auth/LoginScreen.tsx
src/screens/auth/SignUpScreen.tsx

Add UI tests for login and sign up screens.
These test that the proper errors are displayed when the forms are not properly filled out. I tried to cover every case so let me know if I missed one or should add any other edge cases.
Closes #699

Authentication screen tests

---

docs/getting-started.md
src/__tests__/constants.ts
src/__tests__/screens/DashboardGalleryScreen.test.tsx
src/__tests__/screens/DashboardScreen.test.tsx
src/screens/dashboard/DashboardGalleryScreen.tsx
src/screens/dashboard/DashboardScreen.tsx

Dashboard UI tests

---

src/components/SearchInput.tsx

I modified the search input component so that the input would be cleared up submission.
https://github.com/Thenlie/Streamability/assets/34535492/cff48b69-bb36-4d8d-9e31-528a0b0afd22
Closes #668

clear search input after submitting search

---

src/logger.ts

Update the logger methods to allow multiple messages. This mostly matches how `console.log` is implemented.

#731 improve logger class

---

src/components/SearchInput.tsx
src/screens/auth/SignUpScreen.tsx

I resolved a number of chrome errors/warning for our forms. There is one remaining that I was unable to resolve. The code is exactly as MUI shows, so going to call it good for now. 
Closes #647

#647 Resolve form label error

---

src/components/ActorCard.tsx
src/components/index.ts
src/stories/components/ActorCard.stories.ts
src/stories/constants.ts
src/types/tmdb/actor.ts
src/types/tmdb/index.ts

This is mostly a copy of the show card for now. I do like the idea of making this image a circle or something different to add more visual variation, but we can always add a second variant later on.
Closes #750

Create actor card component and storybook

---

src/components/ActorCard.tsx
src/helpers/getMovieUtils.ts
src/helpers/showTypeUtils.ts
src/screens/ShowDetailsScreen.tsx
src/types/tmdb/movie.ts
src/types/tmdb/show.ts
src/types/tmdb/tv.ts

Added a scrollable cast list to the show details page. I thought using the carousel might look to repetitive so I went this route. Open to suggestions.
Closes #594

Add cast list to show detail screen

---

TODO.md
src/components/ActorCard.tsx
src/helpers/getActorUtils.ts
src/helpers/getMovieUtils.ts
src/helpers/index.ts
src/helpers/showTypeUtils.ts
src/routes.tsx
src/screens/ActorDetailScreen.tsx
src/screens/index.ts
src/types/tmdb/actor.ts

Created the actor detail screen at `details/actor/:id`. This contains a carousel of movies and tv shows the actor is credited in. 
The biography of the actor can get quite long so I made it collapsible.
Also worth noting, a movie or tv show credit can be as an actor or as a crew member. This may be something we want to distinguish in the future.
https://drive.google.com/file/d/1wkAnAZTk3Raa157jvntknV9Nmxt51beJ/view?usp=sharing

Actor detail screen

---

src/components/ActorCard.tsx
src/components/loaders/ActorCardLoader.tsx
src/components/loaders/index.ts
src/stories/loaders/ActorCardLoader.stories.ts

Created an actor card skeleton loader. Not yet implemented anywhere.
Closes #753

Create actor card loader component and storybook

---

TODO.md
src/screens/ActorDetailScreen.tsx
src/screens/loaders/ActorDetailLoader.tsx
src/screens/loaders/index.ts

Create actor details screen loader.
Closes #758

Create actor detail screen loader

---

TODO.md
src/screens/ActorDetailScreen.tsx
src/screens/EmptyActorDetailScreen.tsx

Create actor detail empty screen
Closes #757

Create empty actor detail screen

---

src/routes.tsx

Refactored detail screen routes.
Closes #756

Refactor detail routes

---

TODO.md
src/__tests__/screens/DiscoverScreen.test.tsx
src/helpers/getMovieUtils.ts
src/screens/discover/DiscoverScreen.tsx

Create simple UI automation test for the discover screen.

Create basic discover screen test

---

package-lock.json
package.json

Add patch package to post install step so it does not need to be run manually.

Add patch package to postinstall

---

package-lock.json
package.json
src/__tests__/components/ShowPoster.test.tsx
src/__tests__/constants.ts
src/components/ShowPoster.tsx

Created unit test for ShowPoster component. This test everything outlined in the ticket description. A bit of mocking was needed to get the theme working correctly. Other than that, it was fairly straight forward.
This is also the first test made in the components testing suite, so can be used as an example for future component tests.
Closes #722

create basic show poster unit test

---

src/__tests__/components/ShowCard.test.tsx
src/__tests__/screens/LoginScreen.test.tsx
src/__tests__/screens/SignUpScreen.test.tsx

Created basic show card unit test.
Closes #106

ShowCard unit test

---

src/__tests__/components/ActorCard.test.tsx
src/__tests__/constants.ts

Created a basic ActorCard unit test
Closes #773

ActorCard unit test

---

src/__tests__/components/ShowListCard.test.tsx
src/components/Rating.tsx
src/components/ShowListCard.tsx

Created basic unit test for the ShowListCard component. Also refactored the card to consume our custom rating component. 
Closes #724

update show list card to consume rating component

---

.storybook/main.ts
src/__tests__/components/Rating.test.tsx
src/components/Rating.tsx

Created basic rating unit test
Closes #936

Create rating unit test

---

.github/dependabot.yml

@dependabot will now group storybook updates into a single PR. This should smooth out updates since they tend to update all packages at the same time.
Closes #998

Create storybook group in @dependabot config

---

.github/workflows/supabase-ping.yml

Created a basic workflow to ping the supabase db daily to prevent it from sleeping. Will add a production ping in a subsequent PR once this is confirmed working.

#949 create supabase ping workflow

---

.github/workflows/supabase-ping.yml

Finalized supabase ping workflow. 
View a successful run here: https://github.com/Thenlie/Streamability/actions/runs/10363125216
Closes #949

#949 finalize supabase ping workflow

---

.github/workflows/supabase-ping.yml

Needed to get the workflow into main for testing. Now pushing the final version before release.

Develop -> Main v2.0.5

---

TODO.md
src/components/SortFilterHeader.tsx
src/screens/DetailScreen.tsx
src/screens/discover/DiscoverDetailScreen.tsx
src/screens/loaders/SearchResultsLoader.tsx
src/screens/search_results/EmptySearchResults.tsx
src/screens/search_results/SearchResultsHeader.tsx
src/screens/search_results/SearchResultsScreen.tsx
src/screens/search_results/index.ts

Add details screen to the discover trending s

Issue 840 discover details list screen

---

TODO.md
src/components/ShowCarousel.tsx

Centered the empty carousel text
Closes #1066

Center empty carousel text

---

src/index.css

This PR aims to update the background color of the scrollbar to match the app's color scheme

add custom scrollbar styles for better aesthetics

---

index.html
src/components/Banner.tsx
src/components/Navigation.tsx
src/screens/ActorDetailScreen.tsx
src/screens/EmptyActorDetailScreen.tsx
src/screens/EmptyShowDetailsScreen.tsx
src/screens/dashboard/DashboardEmptyGallery.tsx
src/screens/search_results/EmptySearchResults.tsx

This PR contains the updates on the meta description for the index.html and the missing alt attributes on the img elements.

748 fix lighthouse seo audit

---

src/components/ActorCard.tsx
src/screens/ShowDetailsScreen.tsx

This PR aims to separate crew and casts

feat: add crew section to ShowDetailsScreen

---

TODO.md
src/__tests__/screens/FeaturedSearchScreen.test.tsx

- Fix todo file
- Fix feature search unit test

fix: todo file and featured search test

---

src/helpers/getTvUtils.ts

Added the `credits` query parameter to the `getTvDetails` request. Closes #1131

Add cast to TV Shows

---

src/__tests__/components/SeasonCard.test.tsx
src/__tests__/constants.ts
src/components/SeasonCard.tsx
src/components/index.ts
src/components/loaders/SeasonCardLoader.tsx
src/components/loaders/index.ts
src/stories/components/SeasonCard.stories.ts
src/stories/constants.ts
src/stories/loaders/SeasonCardLoader.stories.ts

Season Component, Loaders, and Unit Tests. Closes #1133 
Component:
Loader:
As #673 represents a parent ticket with significant code additions and many sub-tickets—I figure this is a great way to continuously and incrementally monitor, review, and approve code. Where future PRs will be created merging #1134, #1135, #1136, and #1137 into `673-seasons`, and then eventually `673-seasons` into `develop`.

Season Component

---

package-lock.json
package.json
src/__tests__/screens/PageNotFoundScreen.test.tsx

bump mui/material and mui/icons-material to 6.4.2

---

src/components/CastCrewCarousel.tsx
src/index.css
src/screens/ShowDetailsScreen.tsx

Set the cast and crew carousel width to match the show carousel. Moved this section to a dedicated component file.
Closes #1199

move cast and crew section to dedicated component. fix width

---

src/__tests__/components/EpisodeCard.test.tsx
src/components/ActorCard.tsx
src/components/CastCrewCarousel.tsx
src/components/EpisodeCard.tsx
src/screens/ShowDetailsScreen.tsx

combine job & character of duplicate cast/crew members in the cast/crew carousel

---

src/__tests__/components/ShowListCard.test.tsx
src/__tests__/constants.ts
src/supabase/profiles.ts

Add test case for show list card queue button
Closes #939

Add test case for show list card queue button

---

eslint.config.js

update lint ignores
